name: 'binance_analytics'
version: '1.0.0'
config-version: 2

profile: 'binance_pipeline'

model-paths: ["models"]

on-run-start:

  # - "{{ create_raw_binance_trade_realtime_kafka_table() }}"
  # - "{{ create_raw_binance_trade_realtime_persist_kafka_table() }}"
  # - "{{ create_mv_raw_binance_trade_realtime_to_persist_kafka_view() }}"

models:
  binance_analytics:
    # Staging models
    stg:
      +materialized: view

    # Mart models
    mart:
      +materialized: table

      +engine: 'MergeTree()'
      +order_by: 'trade_time, symbol'
      +settings:
        allow_nullable_key: 1
