version: 2

sources:
  - name: binance_raw
    database: raw       
    tables:
      - name: raw_binance_trade_batchjob
        description: "Raw trades from Binance"
      - name: raw_binance_trade_realtime
        description: "Raw trades from Binance"
      - name: raw_binance_trade_realtime_persist
  - name: stg
    database: stg_prod       
    tables:
      - name: stg_binance_trade_batchjob
        description: "Raw trades from Binance"
      - name: stg_binance_trade_realtime

